# Generated by Django 4.2 on 2025-02-25 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers_created', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField()),
                ('attendees', models.ManyToManyField(related_name='meetups_attended', to='users.user')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetups', to='markers.marker')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_owned', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='MeetupPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='rooms/meetup/photos/')),
                ('marker_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='markers.meetup')),
            ],
        ),
        migrations.AddField(
            model_name='marker',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='markers.room'),
        ),
    ]
